/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ruchick;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class CustomersInput extends javax.swing.JFrame {

    /**
     * Creates new form CustomersInput
     */
    public CustomersInput() {
        initComponents();
//        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        btn_lihatmenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(40, 40, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RuChick");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat datang di Rully Chicken!");

        nameInput.setBackground(new java.awt.Color(229, 230, 236));
        nameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameInput.setAlignmentX(3.0F);
        nameInput.setAlignmentY(4.0F);
        nameInput.setBorder(null);
        nameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameInput.setMargin(new java.awt.Insets(2, 15, 2, 15));
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        btn_lihatmenu.setBackground(new java.awt.Color(139, 146, 178));
        btn_lihatmenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_lihatmenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_lihatmenu.setText("Pilih Menu");
        btn_lihatmenu.setBorderPainted(false);
        btn_lihatmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihatmenuActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Masukkan nama anda terlebih dahulu sebelum memesan");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ruchick.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_lihatmenu)
                        .addGap(317, 317, 317))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_lihatmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void btn_lihatmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihatmenuActionPerformed
        // TODO add your handling code here:
        String customerName = nameInput.getText();
        customerName = customerName.toLowerCase();
        if (customerName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "nama harus diisi");
        } else {
            try {
                Connection penghubungdatabase = (Connection)koneksi_database.konfigurasi_database();

                // Check if customerName already exists
                String sql_checkCustomer = "SELECT COUNT(*), customer_id FROM customers WHERE name = ?";
                PreparedStatement checkStatement = penghubungdatabase.prepareStatement(sql_checkCustomer);
                checkStatement.setString(1, customerName);
                ResultSet resultSet = checkStatement.executeQuery();

                resultSet.next();
                int count = resultSet.getInt(1);
                int customerId = resultSet.getInt(2);
                int id_order = 0;

                if (count > 0) {
                    String sql_insertOrders = "INSERT INTO orders (customer_id, total_amount) VALUES (?, 0)";
                    PreparedStatement insOrdersStatement = penghubungdatabase.prepareStatement(sql_insertOrders, Statement.RETURN_GENERATED_KEYS);
                    insOrdersStatement.setInt(1, customerId);
                    insOrdersStatement.executeUpdate();

                    // Get the generated order_id
                    ResultSet generatedKeys = insOrdersStatement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        id_order = generatedKeys.getInt(1);
                    }
                    JOptionPane.showMessageDialog(null, id_order);
                    RuchickMenu form_dashboard = new RuchickMenu(id_order);
                    form_dashboard.setVisible(true);
                    this.setVisible(false);
                } else {
                    // Insert the new customer name
                    String sql_insertCustomer = "INSERT INTO customers (name) VALUES (?)";
                    PreparedStatement insertStatement = penghubungdatabase.prepareStatement(sql_insertCustomer, Statement.RETURN_GENERATED_KEYS);
                    insertStatement.setString(1, customerName);
                    insertStatement.executeUpdate();

                    // Get the generated customer_id
                    ResultSet generatedKeysCustomer = insertStatement.getGeneratedKeys();
                    if (generatedKeysCustomer.next()) {
                        customerId = generatedKeysCustomer.getInt(1);
                    }

                    String sql_insertOrders = "INSERT INTO orders (customer_id, total_amount) VALUES (?, 0)";
                    PreparedStatement insOrdersStatement = penghubungdatabase.prepareStatement(sql_insertOrders, Statement.RETURN_GENERATED_KEYS);
                    insOrdersStatement.setInt(1, customerId);
                    insOrdersStatement.executeUpdate();

                    // Get the generated order_id
                    ResultSet generatedKeysOrders = insOrdersStatement.getGeneratedKeys();
                    if (generatedKeysOrders.next()) {
                        id_order = generatedKeysOrders.getInt(1);
                    }
                    RuchickMenu form_dashboard = new RuchickMenu(id_order);
                    form_dashboard.setVisible(true);
                    this.setVisible(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error! \n" + e);
            }
        }
    }//GEN-LAST:event_btn_lihatmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lihatmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameInput;
    // End of variables declaration//GEN-END:variables
}
