/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.ruchick;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Muhamad Fadhly
 */
public class MenuPelangganInternalForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuPelangganInternalForm
     */
    public MenuPelangganInternalForm() {
        initComponents();
        tambahPanelDariDatabase();
    }
    
    public void tambahPanelDariDatabase() {
        try {
            // Koneksi mySQL
            Connection penghubungdatabase = (Connection)koneksi_database.konfigurasi_database();

            // Query untuk mengambil data dari menu_items
            String sql_select = "SELECT menu_item_id, name, price, description, category, stock, units FROM menu_items";
            PreparedStatement query_select = penghubungdatabase.prepareStatement(sql_select);
            ResultSet resultSet = query_select.executeQuery();

            // Mengatur layout container
            JPanel panelContainer = new JPanel();
            panelContainer.setLayout(new GridLayout(0, 1, 10, 10));
            panelContainer.setBorder(new EmptyBorder(10, 10, 10, 10));

            // Membuat panel untuk setiap item
            while (resultSet.next()) {
                JPanel itemPanel = new JPanel();
                itemPanel.setLayout(new GridLayout(0, 2));

                // Mengambil data dari result set
                String name = resultSet.getString("name");
                int price = resultSet.getInt("price");
                String description = resultSet.getString("description");
                String category = resultSet.getString("category");
                int stock = resultSet.getInt("stock");
                String units = resultSet.getString("units");

                // Menambahkan data ke panel
                itemPanel.add(new JLabel("Nama:"));
                itemPanel.add(new JLabel(name));
                itemPanel.add(new JLabel("Harga:"));
                itemPanel.add(new JLabel(String.valueOf(price)));
                itemPanel.add(new JLabel("Deskripsi:"));
                itemPanel.add(new JLabel(description));
                itemPanel.add(new JLabel("Kategori:"));
                itemPanel.add(new JLabel(category));
                itemPanel.add(new JLabel("Stok:"));
                itemPanel.add(new JLabel(String.valueOf(stock)));
                itemPanel.add(new JLabel("Unit:"));
                itemPanel.add(new JLabel(units));

                // Menambahkan panel item ke container
                panelContainer.add(itemPanel);
            }

            // Menambahkan panel container ke dalam frame utama
            this.getContentPane().add(panelContainer);
            this.pack(); // Menyesuaikan ukuran frame dengan konten
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan: " + e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panelContainer = new javax.swing.JPanel();

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));

        panelContainer.setBackground(new java.awt.Color(255, 255, 255));
        panelContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelContainer.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        scrollPane.setViewportView(panelContainer);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContainer;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
