/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.ruchick;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author Muhamad Fadhly
 */
public class ReportsInternalForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuInternalForm
     */
    public ReportsInternalForm() {
        initComponents();
        setRowColors();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Map<LocalDate, Double> incomeData = getDailyIncome();
        bacaReports();
        getTopSalesItem();
        displayTopSales();
        getMonthlyIncome();
        displayMonthlyIncome();
        getTotalIncome();
        displayTotalIncome();
        displayIncomeChart(createLineChart(incomeData));
        getTotalCustomerToday();
        displayCustomerToday();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    
    
    
    private void bacaReports(){
    DefaultTableModel reportTbl = new DefaultTableModel(){
        @Override
        public boolean isCellEditable (int row, int column){
            return false;
        }
    };
    reportTbl.addColumn("Report ID");
    reportTbl.addColumn("Order Detail ID");
    reportTbl.addColumn("Item Name");
    reportTbl.addColumn("Price");
    reportTbl.addColumn("Date");

    try {
        String perintahSQL_tampilData = "SELECT report_id, order_detail_id, item_name, price, date FROM report";

        Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();

        Statement statementSQL = penghubung_database.createStatement();

        ResultSet hasilSQL = statementSQL.executeQuery(perintahSQL_tampilData);

        while (hasilSQL.next()) {
            reportTbl.addRow(new Object[]{
                hasilSQL.getInt("report_id"),
                hasilSQL.getInt("order_detail_id"),
                hasilSQL.getString("item_name"),
                hasilSQL.getBigDecimal("price"),
                hasilSQL.getDate("date")
            });

            tableReports.setModel(reportTbl);
        }

    } catch (Exception e) {
        e.printStackTrace();
        // Pesan Error kalau gagal
    }
}
    
        // Method untuk menampilkan data di JTable
    public void displayReport(String query) {
        try (
        Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();

        Statement stmt = penghubung_database.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            // Ambil metadata dari result set
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Buat kolom JTable
            DefaultTableModel model = new DefaultTableModel();
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(metaData.getColumnName(i));
            }

            // Isi data ke JTable
            while (rs.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }

            // Set model ke JTable
            tableReports.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
        // Method untuk mengambil item_name paling populer
    public String getTopSalesItem() {
        String query = "SELECT item_name, COUNT(*) as count FROM report GROUP BY item_name ORDER BY count DESC LIMIT 1";
        String topItem = "";

        try (
        Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();

        Statement statementSQL = penghubung_database.createStatement();
        ResultSet rs = statementSQL.executeQuery(query)) {

            if (rs.next()) {
                topItem = rs.getString("item_name");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return topItem;
    }

    // Method untuk menampilkan item_name paling populer di JLabel
    public void displayTopSales() {
        String topSalesItem = getTopSalesItem();
        TopSales.setText( topSalesItem);
    }
    
        // Method untuk menghitung total income bulan ini
    public double getMonthlyIncome() {
        YearMonth currentMonth = YearMonth.now();
        LocalDate startDate = currentMonth.atDay(1);
        LocalDate endDate = currentMonth.atEndOfMonth();
        
        String query = "SELECT SUM(price) as total_income FROM report WHERE date BETWEEN ? AND ?";
        double totalIncome = 0.0;

        try (
                
        Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();

        Statement statementSQL = penghubung_database.createStatement();   
                
             PreparedStatement pstmt = penghubung_database.prepareStatement(query)) {

            pstmt.setDate(1, Date.valueOf(startDate));
            pstmt.setDate(2, Date.valueOf(endDate));
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                totalIncome = rs.getDouble("total_income");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return totalIncome;
    }

    // Method untuk menampilkan total income bulan ini di JLabel
    public void displayMonthlyIncome() {
        double monthlyIncome = getMonthlyIncome();
        Income.setText("Rp " + monthlyIncome + "");
    }

    
        public double getTotalIncome() {
        String query = "SELECT SUM(price) as total_income FROM report";
        double totalIncome = 0.0;

        try (
            Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();
            Statement statementSQL = penghubung_database.createStatement(); 
            ResultSet rs = statementSQL.executeQuery(query)) {

            if (rs.next()) {
                totalIncome = rs.getDouble("total_income");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return totalIncome;
    }

    // Method untuk menampilkan total income di JLabel
    public void displayTotalIncome() {
        double totalIncome = getTotalIncome();
        TotalIncome.setText("Rp " + totalIncome + "");
    }

    // Method untuk memanggil fungsi total_customer_today dan mendapatkan hasilnya
    public int getTotalCustomerToday() {
        String query = "SELECT total_customer_today() AS total_customer_today";
        int totalCustomerToday = 0;

        try (
            Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();
            Statement stmt = penghubung_database.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            if (rs.next()) {
                totalCustomerToday = rs.getInt("total_customer_today");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return totalCustomerToday;
    }

    // Method untuk menampilkan total customer hari ini di JLabel
    public void displayCustomerToday() {
        int totalCustomerToday = getTotalCustomerToday();
        customerToday.setText(String.valueOf(totalCustomerToday));
    }

    // Method untuk mendapatkan data income per hari
    public Map<LocalDate, Double> getDailyIncome() {
     String query = "SELECT date, SUM(price) as daily_income FROM report GROUP BY date ORDER BY date";
     Map<LocalDate, Double> incomeData = new TreeMap<>();

     try (
         Connection penghubung_database = (Connection)koneksi_database.konfigurasi_database();
         Statement stmt = penghubung_database.createStatement();
         ResultSet rs = stmt.executeQuery(query)) {

         while (rs.next()) {
             LocalDate date = rs.getDate("date").toLocalDate();
             double dailyIncome = rs.getDouble("daily_income");
             incomeData.put(date, dailyIncome);
         }

     } catch (Exception e) {
         e.printStackTrace();
     }

     return incomeData;
 }
    
    // Method untuk membuat line chart menggunakan JFreeChart
    public JFreeChart createLineChart(Map<LocalDate, Double> incomeData) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Map.Entry<LocalDate, Double> entry : incomeData.entrySet()) {
            dataset.addValue(entry.getValue(), "Income", entry.getKey());
        }

        return ChartFactory.createLineChart(
                "Daily Income Chart",
                "Date",
                "Income",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
    }
    
        // Method untuk membuat bar chart menggunakan JFreeChart
    public JFreeChart createBarChart(Map<LocalDate, Double> incomeData) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (Map.Entry<LocalDate, Double> entry : incomeData.entrySet()) {
            dataset.addValue(entry.getValue(), "Income", entry.getKey().toString());
        }

        return ChartFactory.createBarChart(
                "Daily Income Chart",
                "Date",
                "Income",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
    }

    // Method untuk menampilkan chart di JPanel
    public void displayIncomeChart(JFreeChart chart) {
//        Map<LocalDate, Double> incomeData = getDailyIncome();
//        JFreeChart lineChart = createLineChart(incomeData);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(panelForChart.getWidth(), panelForChart.getHeight()));
        chartPanel.setMouseWheelEnabled(true);

        panelForChart.removeAll();
        panelForChart.setLayout(new java.awt.BorderLayout());
        panelForChart.add(chartPanel, java.awt.BorderLayout.CENTER);
        panelForChart.validate();
    }

    

    //genrated code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSlider1 = new javax.swing.JSlider();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReports = new javax.swing.JTable();
        buttonToday = new javax.swing.JButton();
        buttonThisMonth = new javax.swing.JButton();
        buttonAllRecords = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TopSales = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelForChart = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Income = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TotalIncome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        customerToday = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        toLineChart = new javax.swing.JButton();
        toBarChart = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setPreferredSize(new java.awt.Dimension(886, 668));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(229, 230, 236));
        jPanel2.setPreferredSize(new java.awt.Dimension(669, 475));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableReports.setForeground(new java.awt.Color(204, 204, 0));
        tableReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Report ID", "Order Detail ID", "Item Name", "Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReports);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 350));

        buttonToday.setBackground(new java.awt.Color(40, 40, 100));
        buttonToday.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        buttonToday.setForeground(new java.awt.Color(255, 255, 255));
        buttonToday.setText("Data Hari Ini");
        buttonToday.setBorderPainted(false);
        buttonToday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTodayActionPerformed(evt);
            }
        });
        jPanel2.add(buttonToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, 40));

        buttonThisMonth.setBackground(new java.awt.Color(40, 40, 100));
        buttonThisMonth.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        buttonThisMonth.setForeground(new java.awt.Color(255, 255, 255));
        buttonThisMonth.setText("Data Bulan Ini");
        buttonThisMonth.setBorderPainted(false);
        buttonThisMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThisMonth.setPreferredSize(new java.awt.Dimension(67, 28));
        buttonThisMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThisMonthActionPerformed(evt);
            }
        });
        jPanel2.add(buttonThisMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 140, 40));

        buttonAllRecords.setBackground(new java.awt.Color(40, 40, 100));
        buttonAllRecords.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        buttonAllRecords.setForeground(new java.awt.Color(255, 255, 255));
        buttonAllRecords.setText("Semua Data");
        buttonAllRecords.setBorderPainted(false);
        buttonAllRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAllRecords.setPreferredSize(new java.awt.Dimension(67, 28));
        buttonAllRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllRecordsActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 130, 40));

        jPanel13.setBackground(new java.awt.Color(139, 146, 178));
        jPanel13.setPreferredSize(new java.awt.Dimension(225, 124));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fast-food.png"))); // NOI18N
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TopSales.setBackground(new java.awt.Color(139, 146, 178));
        TopSales.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TopSales.setForeground(new java.awt.Color(255, 255, 255));
        TopSales.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel13.add(TopSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, 64));

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setText("Top Sales 1#");
        jLabel16.setMaximumSize(new java.awt.Dimension(181, 32));
        jLabel16.setMinimumSize(new java.awt.Dimension(181, 32));
        jLabel16.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 213, 48));

        panelForChart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(139, 146, 178));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_1.png"))); // NOI18N
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Income.setBackground(new java.awt.Color(153, 153, 153));
        Income.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Income.setForeground(new java.awt.Color(255, 255, 255));
        Income.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel8.add(Income, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, 60));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Monthly Income");
        jLabel6.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 231, 48));

        jPanel9.setBackground(new java.awt.Color(139, 146, 178));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revenue_1.png"))); // NOI18N
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TotalIncome.setBackground(new java.awt.Color(153, 153, 153));
        TotalIncome.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        TotalIncome.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel9.add(TotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, 60));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Total Income");
        jLabel7.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 231, 48));

        jPanel11.setBackground(new java.awt.Color(139, 146, 178));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rating.png"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        customerToday.setBackground(new java.awt.Color(153, 153, 153));
        customerToday.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        customerToday.setForeground(new java.awt.Color(255, 255, 255));
        customerToday.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel11.add(customerToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, 60));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Customers Today");
        jLabel11.setPreferredSize(new java.awt.Dimension(56, 39));
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 231, 48));

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Tabel Reports");
        jLabel15.setMaximumSize(new java.awt.Dimension(181, 32));
        jLabel15.setMinimumSize(new java.awt.Dimension(181, 32));
        jLabel15.setPreferredSize(new java.awt.Dimension(56, 39));

        toLineChart.setBackground(new java.awt.Color(40, 40, 100));
        toLineChart.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        toLineChart.setForeground(new java.awt.Color(255, 255, 255));
        toLineChart.setText("Line Chart");
        toLineChart.setBorderPainted(false);
        toLineChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toLineChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLineChartActionPerformed(evt);
            }
        });

        toBarChart.setBackground(new java.awt.Color(40, 40, 100));
        toBarChart.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        toBarChart.setForeground(new java.awt.Color(255, 255, 255));
        toBarChart.setText("Bar Chart");
        toBarChart.setBorderPainted(false);
        toBarChart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBarChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelForChart, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(toLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelForChart, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toLineChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLineChartActionPerformed
        // TODO add your handling code here:
        Map<LocalDate, Double> incomeData = getDailyIncome();
        displayIncomeChart(createLineChart(incomeData));
    }//GEN-LAST:event_toLineChartActionPerformed

    private void buttonTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTodayActionPerformed
        // TODO add your handling code here:
        displayReport("SELECT * FROM report WHERE DATE(date) = CURDATE()");
    }//GEN-LAST:event_buttonTodayActionPerformed

    private void buttonThisMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThisMonthActionPerformed
        // TODO add your handling code here:
        displayReport("SELECT * FROM report WHERE YEAR(date) = YEAR(CURDATE()) AND MONTH(date) = MONTH(CURDATE())");
    }//GEN-LAST:event_buttonThisMonthActionPerformed

    private void buttonAllRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllRecordsActionPerformed
        // TODO add your handling code here:
        displayReport("SELECT * FROM report");
    }//GEN-LAST:event_buttonAllRecordsActionPerformed

    private void toBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBarChartActionPerformed
        // TODO add your handling code here:
        Map<LocalDate, Double> incomeData = getDailyIncome();
        displayIncomeChart(createBarChart(incomeData));
    }//GEN-LAST:event_toBarChartActionPerformed




        private void setRowColors() {
         // Mendapatkan renderer sel default dari tabel
        DefaultTableCellRenderer defaultRenderer = (DefaultTableCellRenderer) tableReports.getDefaultRenderer(Object.class);

        // Mengatur renderer sel kustom untuk mengatur warna latar belakang baris bergantian
        tableReports.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final java.awt.Component c = defaultRenderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // Mengatur warna latar belakang baris bergantian
                if (row % 2 == 0) {
                    c.setBackground(java.awt.Color.WHITE);
                } else {
                    c.setBackground(new java.awt.Color(173, 216, 230));
                }
                c.setForeground(java.awt.Color.BLACK);
                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Income;
    private javax.swing.JLabel TopSales;
    private javax.swing.JLabel TotalIncome;
    private javax.swing.JButton buttonAllRecords;
    private javax.swing.JButton buttonThisMonth;
    private javax.swing.JButton buttonToday;
    private javax.swing.JLabel customerToday;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel panelForChart;
    private javax.swing.JTable tableReports;
    private javax.swing.JButton toBarChart;
    private javax.swing.JButton toLineChart;
    // End of variables declaration//GEN-END:variables
}
